apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  init.sql: |
    -- Set up the user privileges
    SELECT user, host FROM mysql.user;
    SHOW GRANTS FOR 'root'@'%';
    ALTER USER 'root'@'localhost' IDENTIFIED BY 'rootpassword';

