apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==
  MYSQL_USER: amVua2lucw==
  MYSQL_PASSWORD: cm9vdHBhc3N3b3Jk

