apiVersion: v1
kind: ConfigMap
metadata:
  name: springapp-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "jenkins"
  SPRING_DATASOURCE_PASSWORD: "rootpassword"
  SPRING_LOCAL_PORT: "8089"

