apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  annotations:
    container.seccomp.security.alpha.kubernetes.io/pod: "runtime/default"  # Seccomp profile
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 1
  template:
    metadata:
      labels:
        app: springapp
    spec:
      serviceAccountName: default  # Use least-privileged service account or create a specific one
      containers:
      - name: springapp
        image: arijhabbechi/spring-springapp:latest
        ports:
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: springapp-config
        securityContext:
          runAsNonRoot: true  # Run as non-root user
          runAsUser: 10001  # High UID for the container user
          capabilities:
            drop:
              - ALL  # Drop all unnecessary capabilities
        resources:  # Resource requests and limits
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
spec:
  selector:
    app: springapp
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
  type: NodePort
