version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  springapp:
    build: .
    container_name: springapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8089:8089

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "myuser",
        "spring.datasource.password" : "rootpassword"
        }'

