version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=mydatabase   

  springapp:
    build: .
    container_name: springapp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
