---
- hosts: minikube
  become: yes  # Elevated privileges required for setup
  vars:
    minikube_version: "v1.30.1"
    helm_version: "v3.7.0"
    minikube_user: "minikube"

  tasks:
    - name: Ensure basic packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Create directory for Docker's GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Add Docker repository to Apt sources
      copy:
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        dest: /etc/apt/sources.list.d/docker.list
        mode: "0644"

    - name: Update the apt package index after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker and related packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add Docker group
      group:
        name: docker
        state: present

    - name: Add Minikube user to Docker group
      user:
        name: "{{ minikube_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker services
      systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service

    - name: Install Minikube
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube
      command: minikube start --driver=docker

    - name: Create directory for Kubernetes GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Kubernetes public signing key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Set permissions for Kubernetes GPG key
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: "0644"

    - name: Add Kubernetes apt repository
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: "0644"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Install Helm
      get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        dest: /tmp/helm.tar.gz
        mode: '0644'

    - name: Extract Helm archive
      unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Move Helm binary to /usr/local/bin
      command: mv /tmp/linux-amd64/helm /usr/local/bin/helm
