---
- name: Setup Zabbix Server using Docker and MySQL
  hosts: minikube
  become: true
  collections:
    - community.zabbix
  vars:
    # Zabbix variables
    zbx_version: "alpine-6.0-latest"
    zbx_server_port: "10051"
    mysql_port: "3307"
    mysql_host: "192.168.116.136"  

  roles:
    - role: geerlingguy.mysql        
      vars:
        mysql_root_password: "root_pass"
        mysql_databases:
          - name: zabbix
        mysql_users:
          - name: zabbix
            host: "%"
            password: "zabbix"
            priv: "zabbix.*:ALL"
        mysql_port: "3307"

  tasks:
    - name: Pull Zabbix server Docker image
      ansible.builtin.docker_image:
        name: "zabbix/zabbix-server-mysql:{{ zbx_version }}"
        source: pull

    - name: Run Zabbix server container
      ansible.builtin.docker_container:
        name: zabbix-server-mysql
        image: "zabbix/zabbix-server-mysql:{{ zbx_version }}"
        state: started
        restart_policy: always
        env:
          DB_SERVER_HOST: "192.168.116.136"   
          DB_SERVER_PORT: "{{ mysql_port }}"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix"
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
        ports:
          - "{{ zbx_server_port }}:10051"

    - name: Wait for Zabbix to be ready
      uri:
        url: "http://{{ mysql_host }}:{{ zbx_server_port }}/zabbix/api_jsonrpc.php"
        method: GET
        return_content: yes
      register: zabbix_api_status
      until: zabbix_api_status.status == 200
      retries: 10
      delay: 15

    - name: Display Zabbix access information
      ansible.builtin.debug:
        msg: |
          Zabbix server setup is complete!
          Zabbix server is running and connected to MySQL on port {{ mysql_port }}.

