---
- name: Zabbix Environment Setup
  hosts: minikube
  become: yes
  tasks:
    - name: Create Docker network for Zabbix components
      community.docker.docker_network:
        name: zabbix-net
        subnet: 172.20.0.0/16
        ip_range: 172.20.240.0/20

    - name: Start MySQL server instance
      community.docker.docker_container:
        name: mysql-server
        image: mysql:8.0-oracle-alpine-trunk
        state: started
        restart_policy: unless-stopped
        networks:
          - name: zabbix-net
        env:
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          MYSQL_ROOT_PASSWORD: "root_pwd"
        command: "--character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password"

    - name: Start Zabbix Java gateway instance
      community.docker.docker_container:
        name: zabbix-java-gateway
        image: zabbix/zabbix-java-gateway:alpine-trunk
        state: started
        restart_policy: unless-stopped
        networks:
          - name: zabbix-net

    - name: Start Zabbix server instance
      community.docker.docker_container:
        name: zabbix-server-mysql
        image: zabbix/zabbix-server-mysql:alpine-trunk
        state: started
        restart_policy: unless-stopped
        networks:
          - name: zabbix-net
        ports:
          - "10051:10051"
        env:
          DB_SERVER_HOST: "mysql-server"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          MYSQL_ROOT_PASSWORD: "root_pwd"
          ZBX_JAVAGATEWAY: "zabbix-java-gateway"

    - name: Start Zabbix web interface instance
      community.docker.docker_container:
        name: zabbix-web-nginx-mysql
        image: zabbix/zabbix-web-nginx-mysql:alpine-trunk
        state: started
        restart_policy: unless-stopped
        networks:
          - name: zabbix-net
        ports:
          - "80:8080"
        env:
          ZBX_SERVER_HOST: "zabbix-server-mysql"
          DB_SERVER_HOST: "mysql-server"
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          MYSQL_ROOT_PASSWORD: "root_pwd"
